version: '3.8'
services:
  mongoDB:
    image: mongo
    container_name: books-mongodb
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: booksdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootroot