spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # turn-off automatic locator
          lower-case-service-id: true
      # for all - # remove duplicate values of Access-Control-Allow-Credentials and Access-Control-Allow-Origin response headers in cases when both the gateway CORS logic and the downstream add them.
      default-filters: DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes[0]:
        id: books-service-get-books
        uri: lb://books-service/
        predicates[0]: Path=/api/v1/books #/**
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie
      routes[1]:
        id: books-service-get-book
        uri: lb://books-service/
        predicates[0]: Path=/api/v1/books/** #/**
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie

server:
  port: 9090  # port where all requests will be coming
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka, http://localhost2:8762/eureka, http://localhost3:8763/eureka

# trace gateway logs
logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty.http.client: debug